### ISSUE TITLE
--add-description  seems not be implemented in blast2genomegff.py 

### ISSUE THREAD

**Issue by mictadlo** [wrf/genomeGTFtools#18]
Hi,
It appears that `--add-description`  is not implemented because I get `Description=None` with 

```
blast2genomegff.py -p blastp \
-b labVSviridiplantae_hybrid_blastp.out \
-g NbLab330.61k.gff3.rename.gff3 \
--add-description \
-d uniprot-taxonomy-viridiplantae-reviewed-yes.fasta > labVSviridiplantae_hybrid_blastp.gff
```
What did I miss?

Thank you in advance

**Comment by wrf** [comment]
if you want it to extract the description from the Uniprot header, you need the option `-S`
I should make this clearer in the docs, or have `--add-description` automatically turn on `-S`
best

**Comment by wrf** [comment]
added more detail to doc
