### ISSUE TITLE
The different domain genome coordinates for test viral genomes like  ##sequence-region KJ755186.1 1 10774 ##sequence-region NC_007803.1 1 19212 ##sequence-region NC_012532.1 1 10794 ##sequence-region NC_045512.2 1 29903

### ISSUE THREAD

**Issue by NailouZhang** [wrf/genomeGTFtools#20]
Hi, 
I met different domain genome coordinates for ZIKV, sars-cov2,
The script used in genomeGTFtools can't get the exact genome coordinates as their description in NCBI.

Can you gene me some solutions?

I run as fellow,
# I download viral fasta sequence from NCBI,

##sequence-region KJ755186.1 1 10774
##sequence-region NC_007803.1 1 19212
##sequence-region NC_012532.1 1 10794
##sequence-region NC_045512.2 1 29903

ANNOT=testVirus
FilePrefix=Prokka_output
# using prokka find CDS
prokka\
         --outdir $ANNOT --force \
        --prefix $FilePrefix \
       --addmrna\
        --locustag ZNL\
        --kingdom Viruses --gcode 11\
        --metagenome\
         testVirus.fasta

sed -i '/FASTA/,$d' $ANNOT/$FilePrefix.gff
sed -i 's/_mRNA//g' $ANNOT/$FilePrefix.gff

# find domain location with hmmscan
hmmscan --domE 0.1 --cpu 4 --domtblout $ANNOT/$FilePrefix.faa.pfam.tab ~/20T/DataBase/SoftwaresEnsembel/EnTAP/interproscan-5.59-91.0/data/pfam/35.0/pfam_a.hmm $ANNOT/$FilePrefix.faa > stringtie.pfam.log

pfam2gff.py -g $ANNOT/$FilePrefix.gff -i $ANNOT/$FilePrefix.faa.pfam.tab -T > $ANNOT/$FilePrefix.faa.pfam_domains.gff
# delete blank rows
sed -ir '/^$/d' $ANNOT/$FilePrefix.faa.pfam_domains.gff

The cooridinations in $ANNOT/$FilePrefix.faa.pfam_domains.gff different from their description in NCBI.

**Comment by wrf** [comment]
Without seeing the output, I don't know.
That could be a result of hmmscan, where the domain matches from the hmmscan differ from the NCBI annotated domains, or from Uniprot.

**Comment by NailouZhang** [comment]
Hi, 
Thank you.

Now, I try with Pfam-A.full.uniprot.gz linked in
https://pfam-docs.readthedocs.io/en/latest/ftp-site.html,
I can't download Pfam-A.full.ncbi.gz(ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.full.ncbi.gz), I can't get access to this link.

Hope this work well.

Can you recommend other pfam databases?

**Comment by wrf** [comment]
maybe you can try the NCBI CDD
https://www.ncbi.nlm.nih.gov/Structure/cdd/cdd.shtml

**Comment by NailouZhang** [comment]
I think different databases and software will predict different boundaries of the same domain. maybe, It is difficult that the domain genome coordinates we predict or define are the same as NCBI, which may be curated by the professor who knows well with the specific virus.

**Comment by NailouZhang** [comment]
Hi, 
Maybe interproscan can resolve this, In the link https://proteinswebteam.github.io/interpro-blog/2016/06/09/Zika-Virus-and-Microcephaly/, interpro can annotate ZIKV, a virus, well. But, I can't well show a gene-wise coordinates. 

would you like to extend your scripts to covert interproscan.sh output for gene-wise coordinates?

**Comment by wrf** [comment]
I can.
Can you paste a few lines of output?

**Comment by NailouZhang** [comment]
Hi,
Thank you!


# I run interproscan as fellow,
interproscan.sh \
	-cpu 45 \
	-iprlookup \
	-goterms \
	-pa \
        -f proteins.fasta \
        -d Interproscan/ 

# interproscan results as fellow, 
      1 LOCUS_TAG_PREFIX_2g00170        1cd6abff79ad3633e17582eb0e576539        222     Phobius CYTOPLASMIC_DOMAIN      Region of a membrane-bound protein predicted to be outside the membrane, in the cytoplasm.      104     222     -       T       11-11-2022      -       -
      2 LOCUS_TAG_PREFIX_2g00170        1cd6abff79ad3633e17582eb0e576539        222     Phobius TRANSMEMBRANE   Region of a membrane-bound protein predicted to be embedded in the membrane.    20      40      -       T       11-11-2022      -       -
      3 LOCUS_TAG_PREFIX_2g00170        1cd6abff79ad3633e17582eb0e576539        222     TMHMM   TMhelix Region of a membrane-bound protein predicted to be embedded in the membrane.    20      39      -       T       11-11-2022      -       -
      4 LOCUS_TAG_PREFIX_2g00170        1cd6abff79ad3633e17582eb0e576539        222     Hamap   MF_04202        Membrane protein [M].   1       222     43.941757       T       11-11-2022      IPR002574       M matrix/glycoprotein, coronavirus      GO:0016020|GO:0039660|GO:0055036        Reactome: R-HSA-1257604|Reactome:
      5 LOCUS_TAG_PREFIX_2g00170        1cd6abff79ad3633e17582eb0e576539        222     Phobius TRANSMEMBRANE   Region of a membrane-bound protein predicted to be embedded in the membrane.    52      73      -       T       11-11-2022      -       -
      6 LOCUS_TAG_PREFIX_2g00170        1cd6abff79ad3633e17582eb0e576539        222     ProSiteProfiles PS51927 Coronavirus membrane (Cov-M) protein profile.   1       222     68.310905       T       11-11-2022      IPR002574       M matrix/glycoprotein, coronavirus      GO:0016020|GO:0039660|GO:0055036        Reactome:
      7 LOCUS_TAG_PREFIX_2g00170        1cd6abff79ad3633e17582eb0e576539        222     Phobius NON_CYTOPLASMIC_DOMAIN  Region of a membrane-bound protein predicted to be outside the membrane, in the extracellular region.   74      78      -       T       11-11-2022      -       -
      8 LOCUS_TAG_PREFIX_2g00170        1cd6abff79ad3633e17582eb0e576539        222     TMHMM   TMhelix Region of a membrane-bound protein predicted to be embedded in the membrane.    51      73      -       T       11-11-2022      -       -
      9 LOCUS_TAG_PREFIX_2g00170        1cd6abff79ad3633e17582eb0e576539        222     Pfam    PF01635 Coronavirus M matrix/glycoprotein       17      214     6.6E-65 T       11-11-2022      IPR002574       M matrix/glycoprotein, coronavirus      GO:0016020|GO:0039660|GO:0055036        Reactome: R-HSA-1257604|Reactome:
     10 LOCUS_TAG_PREFIX_2g00170        1cd6abff79ad3633e17582eb0e576539        222     Phobius NON_CYTOPLASMIC_DOMAIN  Region of a membrane-bound protein predicted to be outside the membrane, in the extracellular region.   1       19      -       T       11-11-2022      -       -
   
### similar result can from  https://www.ebi.ac.uk/interpro/search/sequence/  with example protein sequence
results like https://www.ebi.ac.uk/Tools/services/rest/iprscan5/result/iprscan5-R20221112-190900-0261-32956277-p2m/tsv
 1 example 538ce3cc6086b9317efa6f6b9b76fbf0        1174    Gene3D  G3DSA:3.30.70.20        -       669     791     1.5E-39 T       12-11-2022      -       -
      2 example 538ce3cc6086b9317efa6f6b9b76fbf0        1174    Pfam    PF17147 Pyruvate:ferredoxin oxidoreductase core domain II       265     347     9.0E-16 T       12-11-2022      IPR033412       Pyruvate:ferredoxin oxidoreductase, core domain II      -       MetaCyc: PWY-1341|MetaCyc: PWY-5104|MetaCyc: PWY-5108|MetaCyc: PWY-5392|MetaCyc: PWY-5483|MetaCyc:>
      3 example 538ce3cc6086b9317efa6f6b9b76fbf0        1174    ProSitePatterns PS00198 4Fe-4S ferredoxin-type iron-sulfur binding region signature.    689     700     -       T       12-11-2022      IPR017900       4Fe-4S ferredoxin, iron-sulphur binding, conserved site -       MetaCyc: PWY-101|MetaCyc: PWY-1341|MetaCyc: PWY-1361|MetaCyc: PWY-1881|MetaCyc: PW>
      4 example 538ce3cc6086b9317efa6f6b9b76fbf0        1174    Pfam    PF01558 Pyruvate ferredoxin/flavodoxin oxidoreductase   426     610     6.3E-34 T       12-11-2022      IPR019752       Pyruvate/ketoisovalerate oxidoreductase, catalytic domain       GO:0016903      MetaCyc: PWY-1341|MetaCyc: PWY-5104|MetaCyc: PWY-5108|MetaCyc: PWY-5392|MetaCyc: PWY-5483|>
      5 example 538ce3cc6086b9317efa6f6b9b76fbf0        1174    SUPERFAMILY     SSF52922        TK C-terminal domain-like       256     411     1.86E-43        T       12-11-2022      IPR009014       Transketolase C-terminal/Pyruvate-ferredoxin oxidoreductase domain II   GO:0003824      MetaCyc: PWY-1121|MetaCyc: PWY-1186|MetaCyc: PWY-1341|MetaCyc: PWY-1861|Me>
      6 example 538ce3cc6086b9317efa6f6b9b76fbf0        1174    Gene3D  G3DSA:3.40.50.920       -       255     415     7.6E-58 T       12-11-2022      IPR009014       Transketolase C-terminal/Pyruvate-ferredoxin oxidoreductase domain II   GO:0003824      MetaCyc: PWY-1121|MetaCyc: PWY-1186|MetaCyc: PWY-1341|MetaCyc: PWY-1861|MetaCyc: PWY-2541|MetaCyc: PWY-260>
      7 example 538ce3cc6086b9317efa6f6b9b76fbf0        1174    ProSiteProfiles PS51379 4Fe-4S ferredoxin-type iron-sulfur binding domain profile.      680     709     9.196906        T       12-11-2022      IPR017896       4Fe-4S ferredoxin-type, iron-sulphur binding domain     -       MetaCyc: PWY-101|MetaCyc: PWY-1341|MetaCyc: PWY-1361|MetaCyc: PWY-1881|Met>
      


# ps. I install interproscan as fellow,
check version of perl python java
####################################################################
#(base) stone@hpc:~/20T/DataBase/SoftwaresEnsembel/EnTAP$ perl -version
#This is perl 5, version 22, subversion 0 (v5.22.0) built for x86_64-linux-thread-multi
#(base) stone@hpc:~/20T/DataBase/SoftwaresEnsembel/EnTAP$ python3 --version
#Python 3.9.13
#(base) stone@hpc:~/20T/DataBase/SoftwaresEnsembel/EnTAP$ java -version
#openjdk version "11.0.13" 2021-10-19
####################################################################


#download
wget https://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/5.59-91.0/interproscan-5.59-91.0-64-bit.tar.gz
wget https://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/5.59-91.0/interproscan-5.59-91.0-64-bit.tar.gz.md5
#Recommended checksum to confirm the download was successful:
md5sum -c interproscan-5.59-91.0-64-bit.tar.gz.md5

#uncompress
mkdir -p interproscan-5.59-91.0
mv interproscan-5.59-91.0-*-bit.tar.gz interproscan-5.59-91.0
tar -pxvzf interproscan-5.59-91.0-*-bit.tar.gz


#first run, require hmm models
python3 setup.py interproscan.properties

### install signalp
tar zxf signalp-4.* -C ~/20T/DataBase/SoftwaresEnsembel/EnTAP/interproscan-5.59-91.0/bin/signalp/4.1 --strip-components 1
#modify ~/20T/DataBase/SoftwaresEnsembel/EnTAP/interproscan-5.59-91.0/bin/signalp/4.1/signalp

location:
BEGIN {
     $ENV{SIGNALP} = 'bin/signalp/4.1';
}


### install tmhmm-2.0c
tar zxf tmhmm-2.0c.Linux.tar.gz -C /tmp
cp /tmp/tmhmm-2.0c/bin/decodeanhmm.Linux_x86_64 ~/20T/DataBase/SoftwaresEnsembel/EnTAP/interproscan-5.59-91.0/bin/tmhmm/2.0c/decodeanhmm
cp /tmp/tmhmm-2.0c/lib/TMHMM2.0.model ~/20T/DataBase/SoftwaresEnsembel/EnTAP/interproscan-5.59-91.0/data/tmhmm/2.0c/TMHMM2.0c.model
rm -rf /tmp/tmhmm-2.0c.Linux.tar.gz
rm -rf /tmp/tmhmm-2.0c


### install phobius101
tar xzf phobius101_linux.tar.gz -C ~/20T/DataBase/SoftwaresEnsembel/EnTAP/interproscan-5.59-91.0/bin/phobius/1.01 --strip-components 3
cp ~/20T/DataBase/SoftwaresEnsembel/EnTAP/interproscan-5.59-91.0/bin/phobius/1.01/decodeanhmm.64bit ~/20T/DataBase/SoftwaresEnsembel/EnTAP/interproscan-5.59-91.0/bin/phobius/1.01/decodeanhmm
rm -rf phobius101_linux.tar.gz


#change cpu and memory
sed -i "s/=--cpu 1/=--cpu 40 /" interproscan-5.59-91.0/interproscan.properties
sed -i "s/=-c 1/=-c 40/" interproscan-5.59-91.0/interproscan.properties
sed -i "s/=-cpu 1/=-cpu 40/" interproscan-5.59-91.0/interproscan.properties
sed -i "s/-Xmx2048m/-Xmx200g/" interproscan-5.59-91.0/interproscan.properties

#run test
interproscan.sh -i protein.fasta -f tsv

**Comment by NailouZhang** [comment]
Another script may do something to help us, in https://github.com/schellt/maker-functional/blob/master/ipr_update_gff.

**Comment by wrf** [comment]
just pushed new version, should make a GFF from the InterProScan. can you please try it?

**Comment by NailouZhang** [comment]
Hi Warren,

Thank you a lot. It works.
