### ISSUE TITLE
bast2gff.py concatenate hits

### ISSUE THREAD

**Issue by mictadlo** [wrf/genomeGTFtools#5]
Hi,
I ran `blast2gff.py`, and I got the following results:
![Screen Shot 2019-09-03 at 12 11 15 PM](https://user-images.githubusercontent.com/588297/64495723-f5cef880-d2e0-11e9-91b4-568e26516a2a.png)

Is there a way to stick together smaller alignments into a region of interest to achieve the below Blast visualisation?

![](http://weatherby.genetics.utah.edu/MAKER/wiki/images/e/e1/Evidence.jpg)

Thank you in advance,

Michal

**Comment by wrf** [comment]
yes, there are two scripts, blast2gff and blast2genomegff. blast2gff was meant for identifying features directly on the DNA, while blast2genomegff was meant for displaying features across exons, such as blast hits of the proteins.
The other script, blast2genomegff.py should be able to create the output you are describing. There are jbrowse examples in the jbrowse folder.
Let me know if you have trouble.
Best
Warren

**Comment by mictadlo** [comment]
Hi Warren,
In the past, I ran tBLASTn. In order to use `blast2genomegff.py` do I need to run `blastx`?

The protein sequence has this header.

```
>NIATv7_g18710.t1       Enoyl-CoA hydratase 2, peroxisomal
```
Is this the correct command `blast2genomegff.py -b blastx.out -p BLASTX  -d NIATTr2.an5.aa.fa --gff-delimiter` to get similar below output?

![image](https://user-images.githubusercontent.com/588297/64628465-cc26e600-d434-11e9-9eb2-34adc69fdbca.png)

Thank you in advance,

Michal

**Comment by wrf** [comment]
I assume you mean query proteins against transcripts, not the whole genome. I think I always run blastx or blastp of my proteins against a database, I'm not even sure it would work with tblastn.

Your command would need something like `-g genes.gff` since the script has to get the exon boundaries from `-g`. The `-gff-delimiter` is only needed if you have some symbols in the gene names that would result in the tabular blast results displaying something different than the gene IDs in the gff.

If you are using input from a program like AUGUSTUS, then I would try to follow the commands here:
https://github.com/wrf/genomeGTFtools#starting-from-augustus-proteins-or-cds

**Comment by mictadlo** [comment]
Hi Warren,
We have got our annotation from BRAKER2 and for your pipelien I used [DIAMOND](https://github.com/bbuchfink/diamond) which has a fast BLASTP.

The input files:

```
> head augustus.hints_utr.aa
>g65211.t1
MPSFYLASFCIMVLSFSITFASGNSVSNKTCIDDATIVLSFGLYQNSCLEAEAIIYSWVE
RAVSQDPRMAASLLRLHFHDCFVNGCDASVLLDDTPNFIGEKTAAPNLNSLRGFEVIDSI
KADLELACPQTVSCADILAIAARDSVVLSGGWRWKVQMGRKDSLTASTKAVNNNIPGPNS
NIATLVSSFQNIGLSLQDMVTLSGAHTIGSARCSTFSSRLNGGGNSDMNLDFLQSLQQLC
SVSDTNITLANLDDMTPSTFDNQYYVNLLSGKGLLVSDQVLASGDDNTREIVQTYVDDPS
AFFDDFRNSMLKMGSLAPPTGTTGEIRVNCRVVN
>g65212.t1
MTSENNFVQAVIPRFDGHYDHQSMLMENVLRSKEFWAVVDGEIQEPGADVLTNAQKTDEA
QKLRDLKAKNYLFQAIDRSILETILCKDTPKQIRDSMKKKYQGNARANNIRRSKPCKAVT
```

```
> head augustus.hints_utr.gff3
NbV1Ch08        AUGUSTUS        gene    7015    29794   0.01    -       .       ID=g1;
NbV1Ch08        AUGUSTUS        mRNA    7015    29794   0.01    -       .       ID=g1.t1;Parent=g1
NbV1Ch08        AUGUSTUS        transcription_end_site  7015    7015    .       -       .       Parent=g1.t1;
NbV1Ch08        AUGUSTUS        three_prime_utr 7015    8531    0.2     -       .       ID=g1.t1.3UTR1;Parent=g1.t1
NbV1Ch08        AUGUSTUS        exon    7015    8747    .       -       .       ID=g1.t1.exon1;Parent=g1.t1;
NbV1Ch08        AUGUSTUS        stop_codon      8532    8534    .       -       0       Parent=g1.t1;
NbV1Ch08        AUGUSTUS        CDS     8532    8747    0.31    -       0       ID=g1.t1.CDS1;Parent=g1.t1
NbV1Ch08        AUGUSTUS        intron  8748    9191    0.49    -       .       Parent=g1.t1;
NbV1Ch08        AUGUSTUS        CDS     9192    9342    0.66    -       1       ID=g1.t1.CDS2;Parent=g1.t1
NbV1Ch08        AUGUSTUS        exon    9192    9342    .       -       .       ID=g1.t1.exon2;Parent=g1.t1;
```


```
> diamond makedb --in uniprot-viridiplantae-reviewed-yes-isoforms.fasta --db uniprot-viridiplantae-reviewed-yes-isoforms -p 4
> diamond blastp --max-target-seqs 5 --evalue 1e-4 --query augustus.hints_utr.aa --db uniprot-viridiplantae-reviewed-yes-isoforms -p 4 --outfmt 6 --out labVSviridiplantae_blastp.out
> head labVSviridiplantae_blastp.out
g65211.t1       sp|O23474|PER40_ARATH   65.7    303     97      2       37      334     48      348     6.3e-112        401.7
g65211.t1       sp|Q96512|PER9_ARATH    52.5    297     135     3       44      334     50      346     1.8e-82 303.9I also tried it with 
g65211.t1       sp|O23237|PER49_ARATH   51.0    298     141     2       42      334     33      330     8.9e-82 301.6
g65211.t1       sp|A7NY33|PER4_VITVI    51.7    331     144     5       7       334     4       321     2.6e-81 300.1
g65211.t1       sp|Q9SI16|PER15_ARATH   51.0    298     141     2       42      334     39      336     2.6e-81 300.1
g65212.t1       sp|P10978|POLX_TOBAC    30.1    408     202     7       210     545     457     853     3.4e-46 184.1
g65212.t1       sp|Q94HW2|POLR1_ARATH   27.8    255     137     5       210     422     500     749     1.8e-23 108.6
g65212.t1       sp|Q9ZT94|POLR2_ARATH   28.6    255     135     5       210     422     479     728     3.5e-22 104.4
g65216.t1       sp|P22895|P34_SOYBN     36.2    105     54      3       28      131     139     231     2.1e-10 63.2
g65216.t2       sp|Q9LT78|RD21C_ARATH   27.5    211     120     5       30      224     135     328     6.5e-18 89.0
```

However, running `blast2genomegff.py` in the below way resulted in an empty GFF file.
```
> python2 /work/waterhouse_team/apps/genomeGTFtools/blast2genomegff.py -b labVSviridiplantae_blastp.out -g augustus.hints.gff3 -d uniprot-viridiplantae-reviewed-yes-isoforms.fasta  -S -x > labVSviridiplantae_blastp.gff
...
WARNING: cannot finish protein at 251 for 393 in []
WARNING: no intervals for POLR1_ARATH in g104060.t1
WARNING: cannot finish protein at 251 for 393 in []
WARNING: no intervals for POLR2_ARATH in g104060.t1
WARNING: cannot finish protein at 251 for 92 in []
WARNING: no intervals for M820_ARATH in g104060.t1
# Removed 16880 hits by shortness
# Removed 60 hits by bitscore
# Removed 72 hits by evalue
# Found 485664 hits for 41387 queries Wed Sep 11 15:25:20 2019
# WARNING: 249709 matches have hits extending beyond gene bounds Wed Sep 11 15:25:20 2019
```

What did I miss?

Thank you in advance,

MIchal

**Comment by wrf** [comment]
Hi Michal,

Sorry this wasn't clear in the doc, I think I see the problem, there are two things: 

The "no intervals" warning means that the gff was not parsed right. There are no rules for gff, which makes it really hard to program anything generic to parse it and make sense of the features. In your case, each exon has its own ID tag (yet for instance, you can see that the stop codons or introns do not), which it reads instead of associating it with a gene. Maybe try `--gff-delimiter "." -G` this would make it ignore gene or mRNA features, and collect exons intervals separately, but then also split the exon IDs at the last "."

I think you might also need to add `-p blastp` because the gff intervals are in nucleotides and the blast coordinates are in amino acids.

Best
Warren

**Comment by mictadlo** [comment]
Hi Warren,
Thank you. This command `blast2genomegff.py -b labVSviridiplantae_blastp.out -g augustus.hints.gff3 -d uniprot-viridiplantae-reviewed-yes-isoforms.fasta  -p blastp --gff-delimiter "." -G -S > labVSviridiplantae_blastp1e-5.gff` works.

The protein `g43736.t1` from `augustus.hints_utr.gff3` is located on `NbV1Ch14` but after running the the above command it ends up on `NbV1Ch03` 

```
> grep "g43736.t1" augustus.hints_utr.gff3
NbV1Ch14	AUGUSTUS	mRNA	136835144	136839500	0.05	+	.	ID=g43736.t1;Parent=g43736
NbV1Ch14	AUGUSTUS	transcription_start_site	136835144	136835144	.	+	.	Parent=g43736.t1;
NbV1Ch14	AUGUSTUS	five_prime_utr	136835144	136835461	0.23	+	.	ID=g43736.t1.5UTR1;Parent=g43736.t1
NbV1Ch14	AUGUSTUS	exon	136835144	136839500	.	+	.	ID=g43736.t1.exon1;Parent=g43736.t1;
NbV1Ch14	AUGUSTUS	start_codon	136835462	136835464	.	+	0	Parent=g43736.t1;
NbV1Ch14	AUGUSTUS	CDS	136835462	136837660	0.66	+	0	ID=g43736.t1.CDS1;Parent=g43736.t1
NbV1Ch14	AUGUSTUS	stop_codon	136837658	136837660	.	+	0	Parent=g43736.t1;
NbV1Ch14	AUGUSTUS	three_prime_utr	136837661	136839500	0.31	+	.	ID=g43736.t1.3UTR1;Parent=g43736.t1
NbV1Ch14	AUGUSTUS	transcription_end_site	136839500	136839500	.	+	.	Parent=g43736.t1;
```

![Screen Shot 2019-09-11 at 10 41 54 PM](https://user-images.githubusercontent.com/588297/64698026-6fcfcf00-d4e5-11e9-9e94-365aa60463d2.png)

Did I miss anything? Why is the annotation file needed?

Thank you in advance,

Michal

**Comment by wrf** [comment]
The idea is to link blast hits to proteins to the genome, the annotation file is the link from the proteins to the genomic coordinates.
I've never seen this bug. Are all of the gene numbers wrong, or just that protein? Can you grep that gene in the diamond results?

**Comment by mictadlo** [comment]
I tested two other proteins and both seems to be misplaced:
```
> grep "g43735.t1" augustus.hints_utr.gff3
NbV1Ch14	AUGUSTUS	mRNA	136828034	136831098	0.01	+	.	ID=g43735.t1;Parent=g43735
NbV1Ch14	AUGUSTUS	transcription_start_site	136828034	136828034	.	+	.	Parent=g43735.t1;
NbV1Ch14	AUGUSTUS	five_prime_utr	136828034	136828151	0.09	+	.	ID=g43735.t1.5UTR1;Parent=g43735.t1
NbV1Ch14	AUGUSTUS	exon	136828034	136828381	.	+	.	ID=g43735.t1.exon1;Parent=g43735.t1;
NbV1Ch14	AUGUSTUS	start_codon	136828152	136828154	.	+	0	Parent=g43735.t1;
NbV1Ch14	AUGUSTUS	CDS	136828152	136828381	0.67	+	0	ID=g43735.t1.CDS1;Parent=g43735.t1
NbV1Ch14	AUGUSTUS	intron	136828382	136828469	0.4	+	.	Parent=g43735.t1;
NbV1Ch14	AUGUSTUS	CDS	136828470	136828542	0.38	+	1	ID=g43735.t1.CDS2;Parent=g43735.t1
NbV1Ch14	AUGUSTUS	exon	136828470	136828542	.	+	.	ID=g43735.t1.exon2;Parent=g43735.t1;
NbV1Ch14	AUGUSTUS	intron	136828543	136830076	0.37	+	.	Parent=g43735.t1;
NbV1Ch14	AUGUSTUS	CDS	136830077	136830649	0.39	+	0	ID=g43735.t1.CDS3;Parent=g43735.t1
NbV1Ch14	AUGUSTUS	exon	136830077	136831098	.	+	.	ID=g43735.t1.exon3;Parent=g43735.t1;
NbV1Ch14	AUGUSTUS	stop_codon	136830647	136830649	.	+	0	Parent=g43735.t1;
NbV1Ch14	AUGUSTUS	three_prime_utr	136830650	136831098	0.13	+	.	ID=g43735.t1.3UTR1;Parent=g43735.t1
NbV1Ch14	AUGUSTUS	transcription_end_site	136831098	136831098	.	+	.	Parent=g43735.t1;
```
```
grep "g43720.t1" augustus.hints_utr.gff3
NbV1Ch14	AUGUSTUS	mRNA	136763914	136766134	0.1	+	.	ID=g43720.t1;Parent=g43720
NbV1Ch14	AUGUSTUS	transcription_start_site	136763914	136763914	.	+	.	Parent=g43720.t1;
NbV1Ch14	AUGUSTUS	five_prime_utr	136763914	136763987	0.37	+	.	ID=g43720.t1.5UTR1;Parent=g43720.t1
NbV1Ch14	AUGUSTUS	exon	136763914	136766134	.	+	.	ID=g43720.t1.exon1;Parent=g43720.t1;
NbV1Ch14	AUGUSTUS	start_codon	136763988	136763990	.	+	0	Parent=g43720.t1;
NbV1Ch14	AUGUSTUS	CDS	136763988	136764188	0.31	+	0	ID=g43720.t1.CDS1;Parent=g43720.t1
NbV1Ch14	AUGUSTUS	stop_codon	136764186	136764188	.	+	0	Parent=g43720.t1;
NbV1Ch14	AUGUSTUS	three_prime_utr	136764189	136766134	0.26	+	.	ID=g43720.t1.3UTR1;Parent=g43720.t1
NbV1Ch14	AUGUSTUS	transcription_end_site	136766134	136766134	.	+	.	Parent=g43720.t1;
```
Would you like that I send you the annotation and blast result files?

Michal

**Comment by wrf** [comment]
I wouldn't need the whole thing, but can you grep that gene in all three files, annotation, blast, and the results?

**Comment by mictadlo** [comment]
```
>g43736.t1
MAGGSTSDLRDRVARLEALIGVTDDPLEMADLITEIYRLKDGADQFRDGIQQSCESTDSV
VEDLRKEVDNLKAEIAVLKLALAAPSQSNEERLKVKIPDPTAFGGARSAKELENFLWDME
QYFVAAKVPDAEKVTITSMYLTGDAKLWWRTRMLDDETAGRPKVDTWEKLRKEMKDQFLP
SNASWLARDHLKRLRQTGSMRDYIKEFSSLMLDVQNMSEDDKLHNFISGMQAWAQNELRR
QAVKDLPSAMAAADSLVDYRSTRSLSEVPSSSKPKKWADKKGEWRKEVREEVIEKGKAID
GVVPNRGGTNRKAVECWTCGGAHLAKDCQNRKRVNALLATEKERDEEGEEVIAYVNPMQV
LNDVSLMNVANNEMNSQSTLMHIEMKIGGKSVMAMIDTGATHTLVCASLVRRYGLKLSKS
SSYVKALNCKSQATVGVAYDVPLSVGNWKGKVSLLVMPIEDFEVILGIDFMKKHCFVPMP
HLDGVMIMNGAAPDFIKAVYPNRRENNQQKVSINSATVINMGVKQNDEIFLAAMVEAKPK
VWLDDIVTPNLDKHGSHLEVLSWGNECKQYVMEKCEAAGQEIIFLEHLVRQYRVRVKSAK
VLVYAERQVPKFGEEMRSFLWSANFYQKFIAEFELLVEGNEAGQDEICVAVYSDVRYGLI
FKSADVKDSLYVKAVNLAKESAVRQYCVEGNKVMLCGTSVAKDQMVDHLSSVSTRTSSLT
SGGGLLDPQNET
```
[labVSviridiplantae_blastp1e-5.gff.txt](https://github.com/wrf/genomeGTFtools/files/3611609/labVSviridiplantae_blastp1e-5.gff.txt)
[augustus.hints_utr.gff3.txt](https://github.com/wrf/genomeGTFtools/files/3611614/augustus.hints_utr.gff3.txt)
[labVSviridiplantae_blastp.out.txt](https://github.com/wrf/genomeGTFtools/files/3611837/labVSviridiplantae_blastp.out.txt)

**Comment by wrf** [comment]
Hi Michal,
I am getting essentially normal output when I run the files you gave. When I blast that protein against uniprot, I do not get any of the hits you are finding in that file, so something must be mixed up. For instance, the protein above is 732 amino acids, but the top hit to Arabidopsis dicer in your file says that the query matched from 10-1527. Something is wrong here.

Are there multiple versions of the augustus output/ annotations/ proteins, or are you working with multiple very similar genomes and something was renamed incorrectly? Maybe try re-running everything from the start.

In any case there was an unrelated bug that I found, which should be fixed now.
Best
Warren
